export {
  deleteCategory,
  deleteImageInstance,
  replaceImageInstance,
  setBrightness,
  setCategories,
  setCategoryVisibility,
  setContrast,
  setExposure,
  setHue,
  setImage,
  setImageInstances,
  setInvertMode,
  setOperation,
  setPenSelectionBrushSize,
  setSaturation,
  setSelectedAnnotation,
  setSelectionMode,
  setSeletedCategory,
  setVibrance,
  setZoomMode,
  setZoomReset,
  slice,
} from "./slice";
